During the CSC8104 coursework practicals, demonstrators will collect frequently asked questions which will then appear here. If you are encountering an issue should also consult the Blackboard discussion boards to see if your issue has already been raised by one of your colleagues.

== Can I use the version of Eclipse IDE provided as part of CS Portable Apps?
No. The version of Eclipse IDE provided as part of CS Portable Apps is an old version which does not support the m2eclipse plugin. We suggest you download a copy of the latest version of Eclipse (Luna) from http://eclipse.org. The version you should download is "Eclipse IDE for Java EE Developers".

== I can't see the .m2 folder mentioned in the tutorial for configuring Maven.
Don't worry. If you do not already have a ".m2" folder, you can simply create one and place the new settings.xml file inside.

== When running `mvn clean test -Parq-jbossas-remote` I get the error `Cannot deploy: test.war`
At the top of the example test which you have been given as part of the quickstart (`ContactRegistrationTest.java`) you will see a `createTestArchive()` method annotated with `@Deployment`.
This method is used to create a small .war file, containing the classes and their dependencies which are needed for your test.
The general `createTestArchive()` method which we recommend is as follows:

``` java
 @Deployment
    public static Archive<?> createTestArchive() {
        //HttpComponents and org.JSON are required by ContactService
        File[] libs = Maven.resolver().loadPomFromFile("pom.xml").resolve(
                "org.apache.httpcomponents:httpclient:4.3.2",
                "org.json:json:20140107",
                "org.codehaus.jackson:jackson-core-asl:1.9.9",
                "org.codehaus.jackson:jackson-mapper-asl:1.9.9",
                "org.codehaus.jackson:jackson-jaxrs:1.9.9"
        ).withTransitivity().asFile();

        Archive<?> archive = ShrinkWrap
            .create(WebArchive.class, "test.war")
            .addPackages(true, "org.jboss.quickstarts.wfk")
            .addAsLibraries(libs)
            .addAsResource("META-INF/test-persistence.xml", "META-INF/persistence.xml")
            .addAsWebInfResource("arquillian-ds.xml")
            .addAsWebInfResource(EmptyAsset.INSTANCE, "beans.xml");
        
        return archive;
    }
```

If you still run into problems, please ask a demonstrator for help.
